steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
args:
- '-c'
- |
  gcloud auth activate-service-account --key-file=${_SERVICE_ACCOUNT_KEY}
  # Export Dialogflow CX agent
  gcloud dialogflow CX agents export \
  --project=${_PROJECT_ID} \
  --location=${_LOCATION} \
  --agent=${_AGENT_ID_TO_EXPORT} \
  --output-path=gs://${_BUCKET_NAME}/${_EXPORT_FILE_NAME}