
steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://agentexportservicekey/agentexport.json', '/workspace/agentexport.json']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'activate-service-account', '--key-file=/workspace/agentexport.json']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        #gcloud auth activate-service-account --key-file=/workspace/agentexport.json
        # Export Dialogflow CX agent
        gcloud alpha dialogflow CX agents export \
          --agent=projects/${_PROJECT_ID}/locations/${_LOCATION}/agents/${_AGENT_ID_TO_EXPORT} \
          --output-file=gs://${_BUCKET_NAME}/${_EXPORT_FILE_NAME}
options:
  logging: CLOUD_LOGGING_ONLY 
