steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://agentexportservicekey/agentexport.json', '/workspace/agentexport.json']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        #gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud dialogflow cx agents export \
          --agent=projects/$PROJECT_ID/locations/$LOCATION/agents/$AGENT_ID \
          --output-file=gs://$BUCKET_NAME/$EXPORT_FILE_NAME
options:
  logging: CLOUD_LOGGING_ONLY
