options:
  substitution_option: ALLOW_LOOSE
substitutions:
  _KEY_FILE_PATH: '/ref/JSON/agentexport.json'

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://agentexportservicekey/service-account-key.json', '${_KEY_FILE_PATH}']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'activate-service-account', '--key-file=${_KEY_FILE_PATH}']
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=${_KEY_FILE_PATH}
        # Export Dialogflow CX agent
        gcloud dialogflow CX agents export \
        --project=${_PROJECT_ID} \
        --location=${_LOCATION} \
        --agent=${_AGENT_ID_TO_EXPORT} \
        --output-path=gs://${_BUCKET_NAME}/${_EXPORT_FILE_NAME}
options:
  logging: CLOUD_LOGGING_ONLY 
